### ISSUE TITLE
"Pulse Master 1" does not display volume percentage changes

### ISSUE THREAD

**Issue by spiralofhope** [andreasvc/cplay#14]
Volume control correctly displays the adjusting percentage for "Pulse Master 0".  However, I do not use "Pulse Master 0".

When I press `v` to change to "Pulse Master 1", the `-` and `+` keys do change the volume, but do not change the displayed volume percent.

I'm using cplay from github current, and Python 2.7.9

> From https://github.com/andreasvc/cplay/issues/14#issuecomment-342459451
> if the output of `pactl` changes it would break again

**Comment by andreasvc** [comment]
The volume control is messy, but I don't really have time to dive into it.

Pulse volume control should be implemented through a proper API instead of parsing the output of shell commands as it is implemented now. You could probably fix the display of the Pulse volume easily, but if the output of `pactl` changes it would break again.

Furthermore, the appropriate system (OSS vs ALSA vs Pulse) should be autodetected. Then, if there are multiple soundcards, and multiple volume controls, the right one should be selected again.

Pull requests welcome!

**Comment by spiralofhope** [comment]
I'm not enough of a programmer to help, but I'll split off a couple of separate issues for your ideas.

**Comment by xi** [comment]
I would like to look into this. @spiralofhope can you explain how to replicate your pulse setup for testing?

**Comment by spiralofhope** [comment]
@xi 
I didn't do anything to set up or customize Pulse.  I'm using the Debian spinoff Devuan.

My audio is built into my motherboard, and I don't have another audio device connected.

I reproduced it again just now, so I know it persists between reboots.  What configuration can I provide, and do you have suggestions on how to give more details?

**Comment by andreasvc** [comment]
It works for me, but I only have Pulse Master 0.
@spiralofhope What's the output of `pactl list` ?

**Comment by spiralofhope** [comment]
I re-tested:

- press `v`
- (It says something like:  `volume 111% (Pulse Master 1)`)
- press and hold `+` or `-`
- (the volume changes but the number does not)
- press `v`
- (It says something like:  `volume 111% (Pulse Master 0)`)
- press and hold `+` or `-`
- (the volume does not change but the number does)

The output of `pactl list` is:
https://gist.github.com/spiralofhope/8c58bceccb4ba6183a3436b27d81be35

The two redacted items are networking-related.

**Comment by spiralofhope** [comment]
I re-tested with the most recent changes (b09a883), and cplay will now slowly skip over all songs in a playlist, not playing any of them.

**Comment by spiralofhope** [comment]
Tested and works, thanks!
